### ISSUE TITLE
Question about time data (timestamps)

### ISSUE THREAD

**Issue by fredchen000** [Optum/retain-keras#13]
Hi tRosenflanz,

Thanks for sharing the work, the well organized code really help a lot when I am trying to understand the model!
Just a small question, why not consider timestamps (ex: to_event, or time delta) as numeric data and provide it with attention weight? I've read through the Appendix A of the original RETAIN paper but still could not understand the meaning of 

> The entire process could be understood such that we use the temporal information not to embed each visit, but to calculate the attentions for the entire visit sequence. This is consistent with our modeling approach where we lose the sequential information in embedding the visit with MLP, then recover the sequential information by generating the attentions using the RNN.

Thanks!

**Comment by tRosenflanz** [comment]
It is essentially the same to treat them separately (and concatenate inside the model) or concatenate right away with a caveat that no dropout will be applied on the time data. Initially I coded this up in a way that disallows dropout on the "time" variables but I doubt it makes a huge practical difference. 

The original text essentially means that timestep data is used to compute attention values (i.e. fed into the LSTM) but isn't embedded as part of the visit encoding (not put through the initial embedding/dense layer like codes are)

**Comment by fredchen000** [comment]
Thanks for your reply!
