### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by sarwart** [Optum/retain-keras#15]
Hi! 

I tried running the code but I received the following error

```
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:600 apply_grad_to_update_var  **
        "Cannot use a constraint function on a sparse variable.")

RuntimeError: Cannot use a constraint function on a sparse variable.
```

I am currently using Keras 2.4.3 ,Tensorflow 2.3.0 and Python 3.6.2.  on my system.

Also , "keras_exp" does not exist in the current version. Can you please guide how to remove these errors? Or any specific version for which this code will work?

**Comment by tRosenflanz** [comment]
Hi.

I would downgrade to Keras 2.1.3 and Tensorflow 1.12 . TF2 brought a lot of changes that would require a bit of code rework.

@jstremme , any chance you have a version that works with TF2?

**Comment by sarwart** [comment]
Downgrading the libraries resulted in some other errors

```
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Anaconda2\deeplearn\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\utils\data_utils.py", line 392, in get_index
    return _SHARED_SEQUENCES[uid][i]
KeyError: 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\utils\data_utils.py", line 555, in get
    inputs = self.queue.get(block=True).get()
  File "D:\Anaconda2\deeplearn\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "retain_train.py", line 364, in <module>
    main(ARGS)
  File "retain_train.py", line 317, in main
    data_test=data_test, y_test=y_test, ARGS=ARGS)
  File "retain_train.py", line 305, in train_model
    callbacks=[checkpoint, log], verbose=1, workers=3, initial_epoch=0)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\engine\training.py", line 2145, in fit_generator
    generator_output = next(output_generator)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\utils\data_utils.py", line 561, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: 0
```
 Author of the Retain paper also recommended your implementation of the paper. I am highly interested in using this for my research. What should I do next?

**Comment by tRosenflanz** [comment]
This looks like a data issue. Can you verify that generator has non 0 length (and data too?)

**Comment by tRosenflanz** [comment]
Also disable multiprocessing and set workers to 1 in the .fit method . This way it should be clearer where the error us happening (right now it is masked by the multiprocessing wrapper)

**Comment by sarwart** [comment]
The data has non-zero length. What do you mean by generator? I checked SquenceBuilder and it is assigning values generally. I also changed the multiprocessing options, but I still get the same error. 

The code runs for only 1 epoch and then ends with a error. The complete log is below:

D:\Anaconda2\deeplearn) D:\MIMIC\reproduce_attempt\retain-keras-master>**python retain_train.py --num_codes=4895**
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
Reading Data
Creating Model
2020-07-31 14:10:56.181580: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Training Model
**Epoch 1/1
163/165 [============================>.] - ETA: 0s - loss: 0.6996 - acc: 0.5460**D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1typ
e' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be
 understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Anaconda2\deeplearn\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\utils\data_utils.py", line 392, in get_index
    return _SHARED_SEQUENCES[uid][i]
KeyError: 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\utils\data_utils.py", line 555, in get
    inputs = self.queue.get(block=True).get()
  File "D:\Anaconda2\deeplearn\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "retain_train.py", line 365, in <module>
    main(ARGS)
  File "retain_train.py", line 318, in main
    data_test=data_test, y_test=y_test, ARGS=ARGS)
  File "retain_train.py", line 306, in train_model
    callbacks=[checkpoint, log], verbose=1, workers=1, initial_epoch=0)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\engine\training.py", line 2213, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "retain_train.py", line 276, in on_epoch_end
    max_queue_size=5)]
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\engine\training.py", line 2437, in predict_generator
    generator_output = next(output_generator)
  File "D:\Anaconda2\deeplearn\lib\site-packages\keras\utils\data_utils.py", line 561, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: 1

**Comment by jstremme** [comment]
> Hi.
> 
> I would downgrade to Keras 2.1.3 and Tensorflow 1.12 . TF2 brought a lot of changes that would require a bit of code rework.
> 
> @jstremme , any chance you have a version that works with TF2?

@tRosenflanz, we have an internal version of this code that works with TF2. I or someone from my team at Optum will plan to add that code to this repo in the upcoming weeks.

**Comment by sarwart** [comment]
Thank you @jstremme

**Comment by lucasliu0928** [comment]
Hi Retain Team,
I am trying to understand the interpretation output, and I wonder if the first column represents the index of the visit?

**Comment by lucasliu0928** [comment]
> Hi!
> 
> I tried running the code but I received the following error
> 
> ```
> D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:600 apply_grad_to_update_var  **
>         "Cannot use a constraint function on a sparse variable.")
> 
> RuntimeError: Cannot use a constraint function on a sparse variable.
> ```
> 
> I am currently using Keras 2.4.3 ,Tensorflow 2.3.0 and Python 3.6.2. on my system.
> 
> Also , "keras_exp" does not exist in the current version. Can you please guide how to remove these errors? Or any specific version for which this code will work?

Hi sarwart,
I solved the verision problem by change all **tf**.functions to **tf.compact.v1**.functions and also change **K**.set_session to **tf.compat.v1.keras.backend**.set_session.

Hope this works for you!

**Comment by sarwart** [comment]
> > Hi!
> > I tried running the code but I received the following error
> > ```
> > D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:600 apply_grad_to_update_var  **
> >         "Cannot use a constraint function on a sparse variable.")
> > 
> > RuntimeError: Cannot use a constraint function on a sparse variable.
> > ```
> > 
> > 
> > I am currently using Keras 2.4.3 ,Tensorflow 2.3.0 and Python 3.6.2. on my system.
> > Also , "keras_exp" does not exist in the current version. Can you please guide how to remove these errors? Or any specific version for which this code will work?
> 
> Hi sarwart,
> I solved the verision problem by change all **tf**.functions to **tf.compact.v1**.functions and also change **K**.set_session to **tf.compat.v1.keras.backend**.set_session.
> 
> Hope this works for you!

Hi lucasliu0928,

Thanks for the suggestion. I did try these changes but it didn't resolve the problem. 

Can you please tell me which versions of the Keras, Tensorflow and Python are you using?

**Comment by tRosenflanz** [comment]
Hi.

@sarwart this issue is hard to debug without a data sample. The error suggests that VALIDATION generator has issues (the error happens in predict function in on_epoch_end)

**Comment by tRosenflanz** [comment]
@lucasliu0928 it would be best if you created another issue to not mix 2 conversations together but first column on print is normally the index of a row- it is fairly meaningless in this context

**Comment by yenlow** [comment]
> > > Hi!
> > > I tried running the code but I received the following error
> > > ```
> > > D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:600 apply_grad_to_update_var  **
> > >         "Cannot use a constraint function on a sparse variable.")
> > > 
> > > RuntimeError: Cannot use a constraint function on a sparse variable.
> > > ```
> > > 
> > > 
> > > I am currently using Keras 2.4.3 ,Tensorflow 2.3.0 and Python 3.6.2. on my system.
> > > Also , "keras_exp" does not exist in the current version. Can you please guide how to remove these errors? Or any specific version for which this code will work?
> > 
> > 
> > Hi sarwart,
> > I solved the verision problem by change all **tf**.functions to **tf.compact.v1**.functions and also change **K**.set_session to **tf.compat.v1.keras.backend**.set_session.
> > Hope this works for you!
> 
> Hi lucasliu0928,
> 
> Thanks for the suggestion. I did try these changes but it didn't resolve the problem.
> 
> Can you please tell me which versions of the Keras, Tensorflow and Python are you using?

The constraint issue seems to [widely reported](https://github.com/tensorflow/tensorflow/issues/33755) with tf 1.15 or 2. I turned it off here by not specifying an embedding constraint (ref: [original code](https://github.com/Optum/retain-keras/blob/4eb41d44e566855eb0e5a0b1df663ce69ef7fdc9/retain_train.py#L160)) and it runs fine for me in tf 1.15 and python 3.7.

**Comment by lucasliu0928** [comment]
> > > Hi!
> > > I tried running the code but I received the following error
> > > ```
> > > D:\Anaconda2\deeplearn\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:600 apply_grad_to_update_var  **
> > >         "Cannot use a constraint function on a sparse variable.")
> > > 
> > > RuntimeError: Cannot use a constraint function on a sparse variable.
> > > ```
> > > 
> > > 
> > > I am currently using Keras 2.4.3 ,Tensorflow 2.3.0 and Python 3.6.2. on my system.
> > > Also , "keras_exp" does not exist in the current version. Can you please guide how to remove these errors? Or any specific version for which this code will work?
> > 
> > 
> > Hi sarwart,
> > I solved the verision problem by change all **tf**.functions to **tf.compact.v1**.functions and also change **K**.set_session to **tf.compat.v1.keras.backend**.set_session.
> > Hope this works for you!
> 
> Hi lucasliu0928,
> 
> Thanks for the suggestion. I did try these changes but it didn't resolve the problem.
> 
> Can you please tell me which versions of the Keras, Tensorflow and Python are you using?

I am using: 
Keras 2.2.4 with tf backend
TensorFlow 2.0.0
Python 3.7.7

**Comment by lucasliu0928** [comment]
> @lucasliu0928 it would be best if you created another issue to not mix 2 conversations together but first column on print is normally the index of a row- it is fairly meaningless in this context

Thanks for the friendly suggestion. This is my first time commenting on GitHub. I was not sure where to post my questions. I will create a separate issue.

**Comment by jstremme** [comment]
Code works with TF2 as of PR #21
