### ISSUE TITLE
Claims data visit level attention

### ISSUE THREAD

**Issue by DanielYWu** [Optum/retain-keras#18]
Hi,

Thank you for this implementation; learned a lot on how to apply DL to claims data!  I was curious as to how you one would aggregate claims data to the visit level. Service date? Given that some facility claims for inpatient hospital stays may span multiple days, curious if there is some processing necessary to get an identifier for visit, which there probably is.

If it's possible, it would be great if there was a sample claims demo dataset, in addition to the MIMIC-III dataset demo.

**Comment by jstremme** [comment]
Good question @DanielYWu.  We have a way of handling this but I need to double check.  I want to say that you can use the discharge date for inpatient claims, but of course it depends on what you're trying to do.  If you would like to match codes from an inpatient claim to a date, typically the best codes to use are the discharge codes, as the clinicians have had time to properly assess the cause of the stay.  By that logic, using discharge date seems appropriate.

**Comment by jstremme** [comment]
For now, no additional demo datasets will be added to the repo.  We are discussing doing more work with this codebase in the future and may want to revisit the idea.
