### ISSUE TITLE
For continuous features

### ISSUE THREAD

**Issue by lucasliu0928** [Optum/retain-keras#19]
If I only use continuous features, what would be the input argument for "num_codes"?

**Comment by jstremme** [comment]
@lucasliu0928, I realize this was posted a while ago, but have you had any luck using RETAIN with just continuous features?  

This was never really a design consideration for us, as we almost always have categorical features.

**Comment by lucasliu0928** [comment]
> 

Yes. I re-implemented it and used RETAIN for continuous features. It got comparable performance with other methods.  I have learned a lot from this model tho I was not able to directly use the implemented version. Thanks!

**Comment by lucasliu0928** [comment]
> @lucasliu0928, I realize this was posted a while ago, but have you had any luck using RETAIN with just continuous features?
> 
> This was never really a design consideration for us, as we almost always have categorical features.

@jstremme, Yes. I re-implemented it and used RETAIN for continuous features. It got comparable performance with other methods. I have learned a lot from this model, though I could not directly use the implemented version. Thanks!

**Comment by jstremme** [comment]
> > @lucasliu0928, I realize this was posted a while ago, but have you had any luck using RETAIN with just continuous features?
> > This was never really a design consideration for us, as we almost always have categorical features.
> 
> @jstremme, Yes. I re-implemented it and used RETAIN for continuous features. It got comparable performance with other methods. I have learned a lot from this model, though I could not directly use the implemented version. Thanks!

Great!  I'm glad you were able to modify the code for continuous features.
