### ISSUE TITLE
Retain for Heart Failure

### ISSUE THREAD

**Issue by asoroosh** [Optum/retain-keras#24]
Hello!

Really great work and quite a useful description of the code -- thank you! 

I have two questions which might sound naive:

1) What event to_event refers to? I initially thought it is heart failure, but it seems to be mortality. Then the to_event refers to the time (in days) until 2025-1-1. Is that a fair understanding?

2) Choi et al. uses heart failure as an event; could a similar thing be done using your keras version and MIMIC-III? The target will be changed to whether a subject has a ICD-9 for heart failure (e.g. 428.0), removing any Dx after the heart failure and recalculating all to_dates to 2025-1-1 similar to the existing code?

Thank you in advance,

**Comment by jstremme** [comment]
@asoroosh, all thanks go to @tRosenflanz!  

You're correct that `to_event` is the number of days until the event we're predicting, in this case, mortality.

Yes, you could predict any event using the approach provided by swapping out the target variable.
