### ISSUE TITLE
Problems using time and numeric information

### ISSUE THREAD

**Issue by JossTG-UPM** [Optum/retain-keras#25]
Thank you so much for the implementation because it is really useful. I have executed the example with MIMIC_III data, first processing the data and then training the model. Everything works fine if I don´t use the time and/or numeric data (with arguments --use_time and --numeric_size) but if I want to use that information I get an error related with the amount of inputs expected by the model. Sorry if it is an obvious error but I don´t have a lot of experience with Python. From my point of view it seems to be that time or numeric data are not been passed to the model (but it is strange because I understand that the example has been tested and should work without problem). 

Below is a copy of the error I get when I try to run the training file, in the hope that someone can tell me what the problem is. Thank you so much in advance for the help.

Training Model
retain_train_old.py:417: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  callbacks=[checkpoint, log], verbose=1, workers=3, initial_epoch=0)
165/165 [==============================] - ETA: 0s - loss: 0.6242 - accuracy: 0.6491/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  layer_config = serialize_layer_fn(layer)
retain_train_old.py:370: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  max_queue_size=5)]
Traceback (most recent call last):
  File "retain_train_old.py", line 476, in <module>
    main(ARGS)
  File "retain_train_old.py", line 429, in main
    data_test=data_test, y_test=y_test, ARGS=ARGS)
  File "retain_train_old.py", line 417, in train_model
    callbacks=[checkpoint, log], verbose=1, workers=3, initial_epoch=0)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 2030, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "retain_train_old.py", line 370, in on_epoch_end
    max_queue_size=5)]
ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1572, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py", line 199, in assert_input_compatibility
        raise ValueError(f'Layer "{layer_name}" expects {len(input_spec)} input(s),'

    ValueError: Layer "model" expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, None) dtype=int64>]

2022-02-03 10:44:26.572863: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

**Comment by jstremme** [comment]
@Yandrak, I'm glad you find this code useful. Would you be willing to share the few lines where you call fit? If you are using the exact code in the repo, I can take a closer look at the current implementation and test with time and numerics. I suspect the issue is that multiple lists are expected as input to the model when using time and numeric info, but not all are being passed. `numeric_size` specifies the number of numeric variables you wish to include.  What are you passing to that argument?

**Comment by JossTG-UPM** [comment]
@jstremme , thank you very much for your prompt reply. I am using the code as it is implemented in the files, and with the same MIMIC-III dataset, I have not changed anything. First, I used the file "process_mimic_modified.py" to get the data with the necessary structure and then I trained the model using the code from the file "retain_train.py". I had no problems with this. But when I wanted to enable the use of temporary data using the --use_time argument is when I get the error I put in the previous comment. And the temporary data is included in the example, that's why I was surprised that it didn't work. I don't know if it has something to do with the versions, but I'm running it on google colab with Keras 2.7.0 and Tensorflow 2.7.0.

**Comment by jstremme** [comment]
After setting recent versions, I'm encountering the same error.  I wonder if the time and numeric features aren't actually being passed from the data prep.  Will need to take a closer look, but unfortunately I can't for a couple days.

**Comment by jstremme** [comment]
@Yandrak, I had a look and updated the code in Pr #27.  Please give the latest version of master a shot.  I tested the training script with the following calls:

Time and numerics:
```
python retain-keras/retain_train.py --num_codes=4895 --use_time --numeric_size=1
```

Just time:
```
python retain-keras/retain_train.py --num_codes=4895 --use_time
```

No time or numerics:
```
python retain-keras/retain_train.py --num_codes=4895
```

**Comment by JossTG-UPM** [comment]
@jstremme Thank you very much for your help and the speed of your response. It works perfectly now. Great job!

**Comment by JossTG-UPM** [comment]
@jstremme Sorry to bother you again, but I think I'm having the same problem with the evaluation file. For some reason it's not passing the numerical and temporal data, I imagine because it needs the same update you did in the training file, but I'm not able to see how to do it. Could you help me with this? 

Edit: I have solved the problem by following the same fix you did in the training script, thanks!!!

**Comment by jstremme** [comment]
@Yandrak, if you would be willing to submit a PR back to the repo with your fix, that would be amazing 😇
