### ISSUE TITLE
Error running the interpretation script

### ISSUE THREAD

**Issue by JoeyTG** [Optum/retain-keras#31]
I have tested the example code, and have had no problems with the processing, training and evaluation scripts. However, when I run the interpretation file, it asks me for the number of the patient I want to analyse, and when I do so, it asks me if I want to see the output predictions. If I answer yes, that's when the error occurs.

I have analysed the code and I know where the error occurs, but I don't understand why the code is like this. Specifically, the error occurs on line 265, and I understand that it is because the dictionary is smaller than the index that is intended to be used. I don't understand why the relevant_indices object is filled with values whose index exceeds the size of the dictionary, as this will always give an error. I explain it in a simpler way with the example I am developing: my dictionary has 45 codes in total and according to the code, when the relevant_indices object is generated it is filled with the codes of the visit and with a series of values higher than the number of codes in the dictionary. As it is logical, when you try to use the dictionary with an index greater than the length of the dictionary (line 265) you get an error because this index does not exist.

Maybe there is something I am not understanding. If someone could help me I would be eternally grateful. I'm running it on google colab with Keras 2.7.0 and Tensorflow 2.7.0.

Edit: I noticed that the error occurs when I use numeric data (numeric_size), because when the script creates the relevant_indices object it does the following:

        relevant_indices = np.append(
            visit_codes,
            range(
                model_parameters.num_codes + 1,
                model_parameters.num_codes + 1 + model_parameters.numeric_size,
            ),
        ).astype(np.int32)

And of course, entering values up to model_parameters.num_codes + 1+model_parameters.numeric_size in the relevant_indices object will never match the length of the dictionary. What am I doing wrong? Thank you very much in advance for your time and help.

Edit2: Sorry, I think I realised what my problem was. I wasn't including the numerical variables in the dictionary from the start (I was just adding the diagnostic codes). I'm going to try to include them, but I'm sure this was the error. Thanks anyway!

**Comment by jstremme** [comment]
@JoeyTG, sorry for the slow reply.  Glad you were able to resolve this!
