### ISSUE TITLE
Question about 'to_event' formatting

### ISSUE THREAD

**Issue by jroberayalas** [Optum/retain-keras#4]
Hello! Quick question: when you say:

> Column 'to_event' is a list of **values** indicating when the respective visit happened. Values have to be ordered from oldest to newest. 

Are these **values** a pd.Timestamp() containing the date of the visit?

**Comment by tRosenflanz** [comment]
No, they should be some numeric value. I usually use days to index event or days since last time step - either will work. You can check appendix A of original RETAIN paper for some more details

**Comment by jroberayalas** [comment]
Great! Thanks for the clarification.
