### ISSUE TITLE
Adding Numerics

### ISSUE THREAD

**Issue by priyakumari85** [Optum/retain-keras#5]
Hi Tim,
This is a question related to adding numerics for training. I am trying to add 'age' as part of the numerics for training. 

Sample data
**Codes** column for an individual with two visits looks like 
[[552,134,75,142,3,143,4],[138,57,3,197]]

**numerics** column for an individual with two visits looks like below
[[87.0027397260274],[87.15616438356165]]

- While training just with medical codes model trains without any error.

- While training with numerics data on top of it, I am getting error 'Input contains NaN, infinity or a value too large for dtype('float32').' 
Loss coming from binary_crossentropy is nan and activation on output layer is sigmoid as its a binary classification. 

Thanks,
Priya

**Comment by tRosenflanz** [comment]
Issues with NAs are normally stemming from data prep. It is likely that you have some of the ages as NA in your data. The error seems to support this. Usual culprit is left joining the medical codes table to a patient table that doesn't have all of the patients in it causing some nulls to pop up.

Unlikely but possible are some precision errors - standardize the age (either min max or standard scale) if you can't detect any NAs in your data

**Comment by priyakumari85** [comment]
Thanks Tim! Was looking for null at wrong place.
