### ISSUE TITLE
pad_data function not correct?

### ISSUE THREAD

**Issue by 2g-XzenG** [Optum/retain-keras#9]
Hi tRosenflanz,

Thanks for sharing your work!
it seems to me that the pad_data function is not correct. Please correct me if I am wrong, your code is trying to pad the input sequence with padding value =0
` def pad_data(data, length_visits, length_codes, pad_value=0):
`
but when you do the masking, your code is trying to mask the last weight, shouldn't you mask the first weight instead? Or set pad_value=len(num_codes)?
`class FreezePadding(Constraint) `
`last_weight = K.cast(K.equal(K.reshape(w[-1, :], (1, K.shape(w)[1])), 0.), K.floatx())`

Thanks!

**Comment by tRosenflanz** [comment]
I think this is a poor choice of default argument for a function on my part but the code is correct overall:
See lines https://github.com/Optum/retain-keras/blob/46186952c57eb09f79962ee377da85269cbfdaf9/retain_train.py#L70
And https://github.com/Optum/retain-keras/blob/46186952c57eb09f79962ee377da85269cbfdaf9/retain_train.py#L75 
Where I explicitly provide different padding values

**Comment by 2g-XzenG** [comment]
You right! Thanks for pointing that out.
I've learned a lot form your code:)
